name: End-to-End Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    # Services removed - we'll start backend manually for better control
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: backend
    
    - name: Start backend server
      run: |
        cd backend
        python main.py &
        sleep 5
        # Wait for backend to be ready
        timeout 30 bash -c 'until curl -f http://localhost:8000/health; do sleep 2; done' || echo "Backend health check timeout"
      
    - name: Install frontend dependencies
      run: npm ci
      working-directory: frontend
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: frontend
    
    - name: Run Playwright tests
      run: npm run test:e2e:ci
      working-directory: frontend
      env:
        CI: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: frontend/test-results/
        retention-days: 30
